version: '3.5'

services:
  crypto-notepad-back:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-notepad-back
    container_name: crypto-notepad-back
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
       - postgres:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
 
volumes:
    postgres: